# Generated by Django 5.1.5 on 2025-03-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='carousel_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='carousel_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='carousel_images/')),
            ],
        ),
    ]
