# Generated by Django 5.1.5 on 2025-03-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
