# Generated by Django 5.1.5 on 2025-03-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_alter_carouselimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='name',
        ),
    ]
