# Generated by Django 5.1.5 on 2025-03-13 10:06

import aplication.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0003_remove_carouselimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessor_title', models.CharField(blank=True, max_length=250, null=250)),
            ],
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_title', models.CharField(blank=True, max_length=450, null=True)),
                ('arrival_image', models.ImageField(blank=True, null=True, upload_to='arrival/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_sms', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Makeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makeup_title', models.CharField(blank=True, max_length=250, null=250)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_title', models.CharField(blank=True, max_length=250, null=250)),
            ],
        ),
        migrations.CreateModel(
            name='Skincare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skincare_title', models.CharField(blank=True, max_length=250, null=250)),
            ],
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image1',
            field=models.ImageField(blank=True, default=aplication.models.default_image, null=True, upload_to='carousel_images/'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image2',
            field=models.ImageField(blank=True, default=aplication.models.default_image, null=True, upload_to='carousel_images/'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image3',
            field=models.ImageField(blank=True, default=aplication.models.default_image, null=True, upload_to='carousel_images/'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=450)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('accessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplication.accessor')),
                ('arrival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplication.arrival')),
                ('makeup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplication.makeup')),
                ('marka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplication.marka')),
                ('skincare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplication.skincare')),
            ],
        ),
    ]
