# Generated by Django 5.1.7 on 2025-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0006_marka_marka_image_marka_marka_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='accessor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='makeup',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marka',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='skincare',
        ),
        migrations.AlterField(
            model_name='arrival',
            name='arrival_title',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
        migrations.DeleteModel(
            name='Accessor',
        ),
        migrations.DeleteModel(
            name='Makeup',
        ),
        migrations.DeleteModel(
            name='Marka',
        ),
        migrations.DeleteModel(
            name='Skincare',
        ),
    ]
