# Generated by Django 5.1.7 on 2025-03-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0007_remove_product_accessor_remove_product_makeup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimage',
            old_name='image2',
            new_name='image',
        ),
    ]
