# Generated by Django 5.1.7 on 2025-03-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0008_rename_image2_carouselimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessor_title', models.CharField(blank=True, max_length=250, null=250)),
            ],
        ),
        migrations.CreateModel(
            name='Makeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makeup_title', models.CharField(blank=True, max_length=250, null=250)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_title', models.CharField(blank=True, max_length=250, null=250)),
            ],
        ),
        migrations.CreateModel(
            name='Skincare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skincare_title', models.CharField(blank=True, max_length=250, null=250)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='accessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplication.accessor'),
        ),
        migrations.AddField(
            model_name='product',
            name='makeup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplication.makeup'),
        ),
        migrations.AddField(
            model_name='product',
            name='marka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplication.marka'),
        ),
        migrations.AddField(
            model_name='product',
            name='skincare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplication.skincare'),
        ),
    ]
