# Generated by Django 5.1.7 on 2025-03-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0010_product_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_title', models.CharField(blank=True, max_length=250, null=250)),
                ('offer_image', models.ImageField(blank=True, null=True, upload_to='offer/')),
            ],
        ),
    ]
