# Generated by Django 5.1.7 on 2025-03-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0012_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
