# Generated by Django 5.1.7 on 2025-03-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0013_alter_offer_offer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
