# Generated by Django 5.1.5 on 2025-03-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0016_shade'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Shade',
        ),
    ]
