# Generated by Django 5.1.5 on 2025-03-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0017_product_description_delete_shade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_title', models.TextField(blank=True, max_length=450, null=True)),
                ('collection_image', models.ImageField(blank=True, null=True, upload_to='collection/')),
            ],
        ),
    ]
