# Generated by Django 5.1.5 on 2025-03-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0020_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
