# Generated by Django 5.1.5 on 2025-03-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0023_product_bestseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bestseller',
        ),
        migrations.DeleteModel(
            name='BestSeller',
        ),
    ]
