# Generated by Django 5.1.5 on 2025-03-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0025_product_is_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
