# Generated by Django 5.1.5 on 2025-04-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0034_checkout_remove_order_ordered_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
