# Generated by Django 5.1.5 on 2025-04-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0036_delete_checkout_rename_created_at_order_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
