# Generated by Django 5.1.5 on 2025-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0037_order_billing_address_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('card', 'Credit/Debit Card')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
