# Generated by Django 5.1.5 on 2025-04-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0039_orderproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
