# Generated by Django 5.1.5 on 2025-04-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0040_delete_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderitems',
        ),
    ]
