# Generated by Django 5.1.5 on 2025-04-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0042_order_ordered_order_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
