# Generated by Django 5.1.5 on 2025-04-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0043_remove_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery')], max_length=10, null=True),
        ),
    ]
